version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: demo-task:1
        LoadBalancerInfo:
          ContainerName: "mycontainer"
          ContainerPort: 80
