version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: demo-task
        LoadBalancerInfo:
          ContainerName: "mycontainer"
          ContainerPort: 80
