version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        LoadBalancerInfo:
          ContainerName: "mycontainer1"  # Container name as defined in the task definition
          ContainerPort: 80  # The container port exposed
